sonar.projectKey=ricartefelipe_angularmind2
sonar.organization=ricartefelipe

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/archive/malha/**

sonar.cpd.exclusions=**/i18n/locales/**,**/archive/malha/**

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
